with open('scanner/service.py', 'r', encoding='utf-8') as f:
    c = f.read()
c = c.replace('["5m", "15m", "1h"]', '["1h", "4h", "1d"]')
c = c.replace('"5m_15m_1h"', '"1h_4h_1d"')
c = c.replace('5m / 15m / 1h', '1h / 4h / 1d')
c = c.replace('tf_aligned.get("15m", True) and tf_aligned.get("1h", True)', 'tf_aligned.get("4h", True) and tf_aligned.get("1d", True)')
c = c.replace('candles_5m = await self._get_candles_for_pair(pair, "5m"', 'candles_1h_aux = await self._get_candles_for_pair(pair, "1h"')
c = c.replace('candles_1h = await self._get_candles_for_pair(pair, "1h"', 'candles_1d_aux = await self._get_candles_for_pair(pair, "1d"')
c = c.replace('is_5m_aligned = _is_bullish(candles_5m)', 'is_1h_aligned = _is_bullish(candles_1h_aux)')
c = c.replace('is_1h_aligned = _is_bullish(candles_1h)', 'is_1d_aligned = _is_bullish(candles_1d_aux)')
c = c.replace('bool(is_5m_aligned and is_15m_bullish and is_1h_aligned)', 'bool(is_1h_aligned and is_4h_bullish and is_1d_aligned)')
c = c.replace('candles = await self._get_candles_for_pair(pair, "15m", limit=120)', 'candles = await self._get_candles_for_pair(pair, "4h", limit=120)')
c = c.replace('"timeframe": "15m"', '"timeframe": "4h"')
c = c.replace('is_15m_bullish = (ema9 >= ema21 * 0.995)', 'is_4h_bullish = (ema9 >= ema21 * 0.995)')
c = c.replace('is_15m_bullish', 'is_4h_bullish')
c = c.replace('The 15m candles above', 'The 4h candles above')
with open('scanner/service.py', 'w', encoding='utf-8') as f:
    f.write(c)
