"""
PROJECT-ALPHA — Adversarial Signal Robustness Engine (Skill 03).

Systematically tests whether trading signals survive noisy and adverse conditions:
  1. OHLC Noise Stress Test (Monte Carlo price perturbation with invariant preservation)
  2. Adverse Execution Stress (Slippage & spread widening impact on Risk-to-Reward)
  3. Latency & Price Drift Stress (Chasing & breakdown protection)
  4. Robustness Gate & Scoring (Multi-factor resilience reporting)
"""

from __future__ import annotations

import copy
import math
import random
from dataclasses import dataclass, field
from typing import Any, Callable

from core.logging import get_logger
from core.types import Signal

logger = get_logger("scanner.adversarial")


@dataclass
class AdversarialStressConfig:
    """Configuration for adversarial stress testing."""

    noise_std_pct: float = 0.5  # Standard deviation of price noise in % (e.g. 0.5%)
    n_simulations: int = 50  # Monte Carlo perturbation iterations
    min_stability_ratio: float = 0.80  # Minimum % of runs retaining valid signal (80%)
    slippage_bps: float = 25.0  # Adverse execution slippage in basis points (25 bps = 0.25%)
    min_acceptable_rr: float = 1.0  # Minimum stressed Risk-to-Reward ratio
    max_chase_progress_pct: float = 0.40  # Max progress toward TP allowed (chasing guard)
    max_invalidation_progress_pct: float = 0.40  # Max progress toward SL allowed (breakdown guard)


@dataclass
class AdversarialStressResult:
    """Report generated by AdversarialStressEngine."""

    is_robust: bool
    stability_score: float  # 0.0 to 1.0
    stressed_rr: float
    max_tolerated_slippage_bps: float
    chase_risk: bool
    invalidation_risk: bool
    nominal_rr: float = 0.0
    mean_score: float = 0.0
    score_std: float = 0.0
    rejection_reasons: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)


class AdversarialStressEngine:
    """
    Adversarial Signal Robustness Engine for PROJECT-ALPHA.
    Validates signals against synthetic noise, adverse execution slippage,
    and market drift before real or paper capital commitment.
    """

    def __init__(self, config: AdversarialStressConfig | None = None) -> None:
        self.config = config or AdversarialStressConfig()

    def inject_ohlc_noise(
        self,
        candles: list[dict[str, Any]],
        noise_std_pct: float | None = None,
        seed: int | None = None,
    ) -> list[dict[str, Any]]:
        """
        Perturbs candle sequence with Gaussian noise while strictly preserving OHLC invariants:
          - High >= max(Open, Close)
          - Low <= min(Open, Close)
          - Low > 0
          - Volume >= 0
        """
        if not candles:
            return []

        sigma = (noise_std_pct if noise_std_pct is not None else self.config.noise_std_pct) / 100.0
        rng = random.Random(seed) if seed is not None else random.Random()

        perturbed: list[dict[str, Any]] = []
        for c in candles:
            c_copy = copy.deepcopy(c)
            open_p = float(c_copy.get("open", c_copy.get("close", 100.0)))
            close_p = float(c_copy.get("close", 100.0))
            high_p = float(c_copy.get("high", max(open_p, close_p)))
            low_p = float(c_copy.get("low", min(open_p, close_p)))
            volume = float(c_copy.get("volume", 0.0))

            # Sample independent noise
            eps_o = rng.gauss(0.0, sigma)
            eps_c = rng.gauss(0.0, sigma)
            eps_h = abs(rng.gauss(0.0, sigma))
            eps_l = abs(rng.gauss(0.0, sigma))
            eps_v = rng.gauss(0.0, sigma * 2.0)

            # Perturb open and close
            p_open = max(1e-8, open_p * (1.0 + eps_o))
            p_close = max(1e-8, close_p * (1.0 + eps_c))

            # Preserve High/Low envelopes
            p_high = max(high_p * (1.0 + eps_h), p_open, p_close)
            p_low = min(low_p * (1.0 - eps_l), p_open, p_close)
            p_low = max(1e-8, p_low)
            p_volume = max(0.0, volume * (1.0 + eps_v))

            c_copy["open"] = p_open
            c_copy["close"] = p_close
            c_copy["high"] = p_high
            c_copy["low"] = p_low
            c_copy["volume"] = p_volume

            perturbed.append(c_copy)

        return perturbed

    def run_monte_carlo_noise_stress(
        self,
        candles: list[dict[str, Any]],
        evaluator_fn: Callable[[list[dict[str, Any]]], Any],
        n_simulations: int | None = None,
        noise_std_pct: float | None = None,
        score_threshold: float = 75.0,
    ) -> tuple[float, list[float], float, float]:
        """
        Runs Monte Carlo noise stress across N perturbed datasets.
        Returns:
          (stability_ratio, list_of_scores, mean_score, std_score)
        """
        if not candles:
            return 0.0, [], 0.0, 0.0

        n_sims = n_simulations or self.config.n_simulations
        noise_pct = noise_std_pct or self.config.noise_std_pct

        scores: list[float] = []
        passes = 0

        for i in range(n_sims):
            perturbed_candles = self.inject_ohlc_noise(
                candles, noise_std_pct=noise_pct, seed=i + 42
            )
            raw_res = evaluator_fn(perturbed_candles)

            # Normalize evaluator response
            if isinstance(raw_res, bool):
                score = 100.0 if raw_res else 0.0
                is_pass = raw_res
            elif isinstance(raw_res, (int, float)):
                score = float(raw_res)
                is_pass = score >= score_threshold
            elif isinstance(raw_res, dict):
                score = float(raw_res.get("score", 0.0))
                is_pass = bool(raw_res.get("passed", score >= score_threshold))
            else:
                score = 0.0
                is_pass = False

            scores.append(score)
            if is_pass:
                passes += 1

        stability_ratio = passes / max(1, n_sims)
        mean_score = sum(scores) / max(1, len(scores))
        variance = sum((s - mean_score) ** 2 for s in scores) / max(1, len(scores))
        std_score = math.sqrt(variance)

        return stability_ratio, scores, mean_score, std_score

    def stress_test_execution_rr(
        self,
        entry_price: float,
        sl_price: float,
        tp_price: float,
        slippage_bps: float | None = None,
        min_acceptable_rr: float | None = None,
        is_long: bool = True,
    ) -> tuple[bool, float, float, float]:
        """
        Calculates stressed Risk-to-Reward under adverse execution slippage.
        Returns:
          (passed, stressed_rr, max_tolerated_slippage_bps, nominal_rr)
        """
        slip_bps = slippage_bps if slippage_bps is not None else self.config.slippage_bps
        slip_frac = slip_bps / 10000.0
        target_rr = (
            min_acceptable_rr if min_acceptable_rr is not None else self.config.min_acceptable_rr
        )

        if entry_price <= 0:
            return False, 0.0, 0.0, 0.0

        if is_long:
            r0 = tp_price - entry_price  # Nominal reward
            k0 = entry_price - sl_price  # Nominal risk
            delta_t = tp_price + entry_price
            delta_s = entry_price + sl_price

            # Stressed execution prices
            p_entry_adv = entry_price * (1.0 + slip_frac)
            p_tp_adv = tp_price * (1.0 - slip_frac)
            p_sl_adv = sl_price * (1.0 - slip_frac)

            stressed_reward = p_tp_adv - p_entry_adv
            stressed_risk = p_entry_adv - p_sl_adv
        else:
            r0 = entry_price - tp_price
            k0 = sl_price - entry_price
            delta_t = entry_price + tp_price
            delta_s = sl_price + entry_price

            p_entry_adv = entry_price * (1.0 - slip_frac)
            p_tp_adv = tp_price * (1.0 + slip_frac)
            p_sl_adv = sl_price * (1.0 + slip_frac)

            stressed_reward = p_entry_adv - p_tp_adv
            stressed_risk = p_sl_adv - p_entry_adv

        nominal_rr = (r0 / k0) if k0 > 0 else 0.0

        if stressed_risk <= 0 or stressed_reward <= 0:
            stressed_rr = 0.0
        else:
            stressed_rr = stressed_reward / stressed_risk

        # Analytical maximum tolerated slippage before R:R drops below target_rr
        denom = delta_t + target_rr * delta_s
        numer = r0 - target_rr * k0
        if numer <= 0 or denom <= 0:
            max_tolerated_bps = 0.0
        else:
            max_tolerated_bps = (numer / denom) * 10000.0

        passed = stressed_rr >= target_rr
        return passed, round(stressed_rr, 3), round(max_tolerated_bps, 1), round(nominal_rr, 3)

    def evaluate_latency_drift(
        self,
        entry_price: float,
        current_price: float,
        sl_price: float,
        tp_price: float,
        is_long: bool = True,
        max_chase_pct: float | None = None,
        max_inval_pct: float | None = None,
    ) -> tuple[bool, bool, list[str]]:
        """
        Detects chasing and invalidation due to market latency/drift.
        Returns:
          (chase_risk, invalidation_risk, reasons)
        """
        chase_limit = (
            max_chase_pct if max_chase_pct is not None else self.config.max_chase_progress_pct
        )
        inval_limit = (
            max_inval_pct if max_inval_pct is not None else self.config.max_invalidation_progress_pct
        )
        reasons: list[str] = []
        chase_risk = False
        invalidation_risk = False

        if is_long:
            tp_dist = tp_price - entry_price
            sl_dist = entry_price - sl_price

            # Progress towards TP (Chasing)
            if tp_dist > 0 and current_price > entry_price:
                progress_tp = (current_price - entry_price) / tp_dist
                if progress_tp >= chase_limit:
                    chase_risk = True
                    reasons.append(
                        f"Chase risk: Price has already completed {progress_tp*100:.1f}% of target distance"
                    )

            # Progress towards SL (Breakdown)
            if sl_dist > 0 and current_price < entry_price:
                progress_sl = (entry_price - current_price) / sl_dist
                if progress_sl >= inval_limit:
                    invalidation_risk = True
                    reasons.append(
                        f"Invalidation risk: Price has already degraded {progress_sl*100:.1f}% towards stop loss"
                    )
        else:
            tp_dist = entry_price - tp_price
            sl_dist = sl_price - entry_price

            if tp_dist > 0 and current_price < entry_price:
                progress_tp = (entry_price - current_price) / tp_dist
                if progress_tp >= chase_limit:
                    chase_risk = True
                    reasons.append(
                        f"Chase risk: Short price has already completed {progress_tp*100:.1f}% of target distance"
                    )

            if sl_dist > 0 and current_price > entry_price:
                progress_sl = (current_price - entry_price) / sl_dist
                if progress_sl >= inval_limit:
                    invalidation_risk = True
                    reasons.append(
                        f"Invalidation risk: Short price has degraded {progress_sl*100:.1f}% towards stop loss"
                    )

        return chase_risk, invalidation_risk, reasons

    def evaluate_signal_robustness(
        self,
        signal: Signal,
        candles: list[dict[str, Any]] | None = None,
        evaluator_fn: Callable[[list[dict[str, Any]]], Any] | None = None,
        current_price: float | None = None,
    ) -> AdversarialStressResult:
        """
        Orchestrates full adversarial stress testing of a domain Signal:
          - Derives entry, TP, and SL according to PROJECT-ALPHA guidelines or payload
          - Evaluates slippage & spread stress
          - Evaluates latency drift (if current_price provided)
          - Evaluates Monte Carlo noise robustness (if candles and evaluator_fn provided)
        """
        payload = signal.raw_payload or {}
        entry_price = float(
            payload.get("price")
            or payload.get("close")
            or payload.get("entry_price")
            or 0.0
        )
        if entry_price <= 0.0 and candles:
            entry_price = float(candles[-1].get("close", 0.0))

        # Determine Target Profit (TP) and Stop Loss (SL) based on PROJECT-ALPHA rules:
        # Standard Score Signals (80 - 89 Score): Target 4.6% - 6.0% TP, 3.5% - 5.0% SL
        # Elite Signals (90+ Score): Target 20.0% - 25.0% TP, 3.5% - 5.0% SL
        if "take_profit" in payload:
            tp_price = float(payload["take_profit"])
        else:
            tp_pct = 0.20 if signal.score >= 90 else 0.05
            tp_price = entry_price * (1.0 + tp_pct)

        if "stop_loss" in payload:
            sl_price = float(payload["stop_loss"])
        else:
            sl_pct = 0.04
            sl_price = entry_price * (1.0 - sl_pct)

        reasons: list[str] = []

        # 1. Execution Slippage Stress Test
        rr_passed, stressed_rr, max_slip_bps, nominal_rr = self.stress_test_execution_rr(
            entry_price=entry_price,
            sl_price=sl_price,
            tp_price=tp_price,
            slippage_bps=self.config.slippage_bps,
            min_acceptable_rr=self.config.min_acceptable_rr,
            is_long=True,
        )
        if not rr_passed:
            reasons.append(
                f"Adverse slippage stress failed: Stressed R:R {stressed_rr:.2f} < threshold {self.config.min_acceptable_rr:.2f}"
            )

        # 2. Latency Drift Stress Test
        chase_risk = False
        inval_risk = False
        if current_price is not None and current_price > 0:
            chase_risk, inval_risk, drift_reasons = self.evaluate_latency_drift(
                entry_price=entry_price,
                current_price=current_price,
                sl_price=sl_price,
                tp_price=tp_price,
                is_long=True,
                max_chase_pct=self.config.max_chase_progress_pct,
                max_inval_pct=self.config.max_invalidation_progress_pct,
            )
            reasons.extend(drift_reasons)

        # 3. Monte Carlo Noise Stress Test (if candles and evaluator provided)
        stability_score = 1.0
        mean_score = float(signal.score)
        std_score = 0.0
        if candles and evaluator_fn:
            stability_score, _, mean_score, std_score = self.run_monte_carlo_noise_stress(
                candles=candles,
                evaluator_fn=evaluator_fn,
                n_simulations=self.config.n_simulations,
                noise_std_pct=self.config.noise_std_pct,
                score_threshold=75.0,
            )
            if stability_score < self.config.min_stability_ratio:
                reasons.append(
                    f"Monte Carlo noise stability failed: {stability_score*100:.1f}% < min {self.config.min_stability_ratio*100:.1f}%"
                )

        is_robust = len(reasons) == 0 and rr_passed and not chase_risk and not inval_risk

        return AdversarialStressResult(
            is_robust=is_robust,
            stability_score=round(stability_score, 3),
            stressed_rr=stressed_rr,
            max_tolerated_slippage_bps=max_slip_bps,
            chase_risk=chase_risk,
            invalidation_risk=inval_risk,
            nominal_rr=nominal_rr,
            mean_score=round(mean_score, 1),
            score_std=round(std_score, 2),
            rejection_reasons=reasons,
            details={
                "entry_price": entry_price,
                "sl_price": sl_price,
                "tp_price": tp_price,
                "slippage_bps": self.config.slippage_bps,
            },
        )
